import 'dart:ffi';

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/cupertino.dart';
import 'package:womenhealth/Model/User_Diet.dart';
import 'package:womenhealth/Model/user.dart';
import 'package:womenhealth/Service/FirestoreService.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:womenhealth/Utils/data/local_food_database.dart';

class FoodViewModel with ChangeNotifier {
  final FirestoreService _firestoreService = FirestoreService('foods');
  LocalFood localFood = LocalFood();
  final nutritionApiKey = "fU9y72p/j2sGb2Tdw0j6/g==E0H80ltgZ4HNggFB";

  List<String> foods = [
    "Milk",
    "Buttermilk",
    "Kefir",
    "Goat milk",
    "Non-dairy milk",
    "Soy milk",
    "Almond milk",
    "Rice milk",
    "Coconut milk",
    "Yogurt",
    " Chipotle sauce",
    "Dill sauce",
    "Onion sauce",
    "Ranch sauce",
    "Spinach sauce",
    "Zatziki sauce",
    "Vegetable sauce",
    "Yogurt parfait",
    "Frozen yogurt",
    "Frozen yogurt sandwich",
    "Frozen yoghurt bar",
    "Frozen yoghurt cone",
    "Chocolate milk",
    "Hot chocolate / Cocoa",
    "Strawberry milk",
    "Eggnog",
    "Milk shake",
    "Licuado",
    "Fruity smoothie",
    "Fruity smoothie juice drink",
    "Chocolate milk drink",
    "Baby food",
    "Whey",
    "Cocoa powder",
    "Chocolate drink powder",
    "Strawberry drink powder",
    "Cream",
    "Coffee cream",
    "Whipped topping",
    "Sour cream",
    "Dip",
    "Ice cream",
    "Gelato",
    "Ice cream bar",
    "Ice cream bar",
    "Ice cream sandwich",
    "Ice cream cookie sandwich",
    "Ice cream cone",
    "Ice cream soda ",
    "Ice cream sundae",
    "Banana split",
    "Light ice cream",
    "Light ice cream sandwich",
    "Light ice cream stick",
    "Cream",
    "Light ice cream cone",
    "Sorbet ",
    "Pudding",
    "Custard",
    "Börek",
    "Creme brulee",
    "Firni",
    "Banana pudding",
    "Mousse",
    "Milk dessert",
    "Tiramisu",
    " Custard pudding",
    "White sauce",
    "Cheese",
    "Queso Anejo",
    "Queso Asadero",
    "Queso Fresco",
    "Queso cotija",
    "Cottage cheese",
    "Puerto Rican feta cheese",
    "Cream cheese",
    "Cheese spread",
    "Cream cheese",
    "Cheese spread",
    "Cream cheese paste",
    "Imitation cheese",
    "Cheese ball",
    "Artichoke sauce",
    "Spinach",
    "Seafood sauce",
    "Cheese sauce",
    "Cheese pizza topping",
    "Vegetable pizza topping",
    "Meat pizza topping",
    "Meat topping",
    "Cheese fondue",
    "Cheese soufflé",
    "Welsh rarebit",
    "Cheese sandwich",
    "Grilled cheese sandwich",
    "Cheese sauce",
    "Alfredo sauce",
    "Mozzarella sticks",
    "Mozzarella cheese",
    "Cheddar cheese soup",
    "Beer cheese soup",
    "Meat",
    "Meat sticks",
    "Minced meat",
    "Beef",
    "Steak",
    "Beef steak",
    "Corned beef",
    "Beef brisket",
    "Ground beef",
    "Ground beef",
    "Beef jerky",
    "Pork",
    "Pork jerky",
    "Pork chop",
    "Pork steak",
    "Ham",
    "Pork roast",
    "Roast pork pieces",
    "Pork roll",
    "Canadian bacon",
    "Bacon",
    "Bacon",
    "Salt pork",
    "Pork ears",
    "Pork skin shells",
    "Pork skin",
    "Meat stick",
    "Lamb",
    "Lamb chop",
    "Lamb knees",
    "Goat",
    "Goat head",
    "Goat ribs",
    "Veal",
    "Veal cutlet",
    "Veal cutlet",
    "Fake chicken leg",
    "Beef patties",
    "Rabbit",
    "Venison sausage",
    "Venison chop",
    "Elk/elk ribs",
    "Deer",
    "Bison",
    "Opossum",
    "Ostrich",
    "Chicken",
    "Chicken breast",
    "Chicken legs",
    "Chicken drumstick",
    "Chicken legs",
    "Chicken legs",
    "Chicken wings",
    "Chicken wings",
    "Chicken skin",
    "Chicken feet",
    "Chicken patties",
    "Chicken fillet",
    "Chicken wings",
    "Chicken tenders",
    "Fried chicken pieces",
    "Turkey",
    " Turkey light",
    "Turkey bacon",
    "Duck",
    "Goose",
    "Cornish game hen",
    "Quail",
    "Pheasant",
    "Chicken stick",
    "Turkey stick",
    "Beef liver",
    "Chicken liver",
    "Liver pate",
    "Sweet rolls",
    "Tongue roast",
    "Tripe",
    "Chitterlings",
    "Pork maw",
    " Gizzard",
    "Frankfurter",
    "Beef sausage",
    "Blood sausage",
    "Bratwurst",
    "Chorizo",
    "Head cheese",
    "Knockwurst",
    "Mortadella",
    "Bacon",
    "Pepperoni",
    "Polish sausage",
    "Italian sausage",
    "Sausage",
    "Pork sausage",
    "Pork sausage rice links",
    "Vienna sausage",
    "Lunch meat with ham",
    "Liver sausage",
    "Turkey ham",
    "Meat paste",
    "Chicken salad paste",
    "Ham salad paste",
    "Fish",
    "Fish stick",
    "Anchovy",
    "Carp",
    "Catfish",
    "Cod",
    "Eel",
    "Halibut",
    "Haddock",
    "Halibut",
    "Herring",
    "Mackerel",
    "Ocean perch",
    "Perch",
    "Pike",
    "Pork",
    "Salmon",
    "Sardine",
    "Sea Bass",
    "Swordfish",
    "Trout",
    "Tuna",
    "Whiting",
    "Tilapia",
    "Frog legs",
    "Octopus",
    "Roe",
    "Squid",
    "Turtle",
    " Oysters",
    "Crab",
    "Crawfish",
    "Lobster",
    "Mussels",
    "Oysters",
    "Scallops",
    "Shrimps",
    "Snails",
    "Beef goulash",
    "Beef claret",
    "Beef stew",
    "Chili con carne",
    "Chili con carne without beans",
    "Beef sloppy joe",
    "Salisbury steak",
    "Beef stroganoff",
    "Swedish meatballs",
    "Steak teriyaki",
    "Beef curry",
    " Boiled seasoned minced meat",
    "Steak tartare",
    "Meatballs",
    "Boiled dried beef",
    "Stuffed roast",
    "Ham stroganoff",
    "Sausage sauce",
    "Pork stew",
    "Frankfurters",
    "Boiled pork",
    "Boiled goat",
    "Veal scallops",
    "Veal Marsala",
    "Veal parmigiana",
    "Veal cordon bleu",
    "Venison",
    "Spaghetti sauce",
    "Boiled chicken",
    "Curry chicken",
    "Orange chicken",
    "Sesame chicken",
    "Chicken kiev",
    "Stuffed chicken",
    "Crab empire",
    "Fish timbale",
    "Lobster newburg",
    "Shrimp cocktail",
    "Seafood newburg",
    "Seafood sauce",
    "Fish sauce",
    "Shrimp scampi",
    "Fish moochim",
    "Fish curry",
    "Shrimp teriyaki",
    "Ceviche",
    "Tomato based crabs in sauce",
    "Prawns in garlic sauce",
    "Boiled cod",
    "Corned beef hash browns",
    "Biryani",
    "Made into meatballs",
    "Beef wellington",
    "Corned beef patties",
    "Boiled corned beef",
    "Ham croquettes",
    "Boiled pork feet",
    "Stuffed pork roast",
    "Cod ball",
    "Crab cake",
    "Fish cake",
    "Gefilte fish ",
    "Salmon cake",
    "Salmon loaf",
    "Tuna loaf",
    "Tuna cake",
    "Oyster cake",
    "Oyster spring rolls",
    "Oyster Casino",
    "Mackerel cake",
    "Widd fish cake",
    "Shrimp cakes",
    "Shrimp toast",
    "Seafood reconstructed",
    "Seafood soufflé",
    "Tuna noodle casserole",
    "Poached salmon",
    "Viennese sausages boiled",
    "Liver dumpling",
    "Shepherd's pastry",
    "Beef pastry",
    "Stuffed cabbage",
    "Stuffed grape leaves",
    "Beef pastry",
    "Stuffed green peppers",
    "Ham pastry",
    " Pork fricassee",
    "Beef fricassee",
    "Beef stew",
    "Rabbit stew",
    "Boiled rabbit",
    "Chicken fricassee",
    "Paella",
    "Seafood stew",
    "Shrimp chow mein",
    "Shrimp creole",
    "Tuna fritter",
    "Bouillabaisse",
    "Oyster pie",
    "Cod",
    "Biscayne cod",
    "Casserole",
    "Goulash",
    "Meat pie",
    "Chow mein",
    "Brunswick casserole",
    "Boiled various meats",
    "Boiled tripe",
    "Okra",
    "Jambalaya",
    "Beef shish kebab",
    "Swiss steak",
    "Beef rolls",
    "Sichuan beef",
    "Hunan beef",
    "Kung Pao beef",
    "Pepper steak",
    "Beef salad",
    "Beef taco filling: beef",
    "Stir-fried beef",
    "Seasoned shredded soup meat",
    "Cabbage",
    "Greens",
    "Kung Pao pork",
    "Moo Shu pork",
    "Pork hash",
    "Pork shish kebab",
    "Pork chop boiled",
    "Beef goulash",
    "Lamb shish kebab",
    "General Tso chicken",
    "Kung pao chicken",
    "Almond chicken",
    "Asian chicken",
    "Crab salad",
    "Lobster salad",
    "Salmon salad",
    "Tuna salad",
    "Shrimp salad",
    "Seafood salad",
    "Shrimp garden salad",
    "Made of crab salad",
    "Seafood garden salad",
    "Oyster Rockefeller",
    "Lomi salmon",
    "Shrimp shish kebab",
    "Kung Pao shrimp",
    "Tuna casserole",
    "Fish shish kebab",
    "Fried fish",
    "Octopus salad",
    "Cod salad",
    "Lau lau",
    "Julienne salad",
    "Liver",
    "Liver",
    "Boiled chitterlings",
    "Boiled gizzards",
    "Sandwich",
    "Beef sandwich",
    "Wrap sandwich",
    "Beef sandwich",
    "Beef barbecue submarine sandwich",
    "Cheeseburger slider",
    "Cheeseburger",
    "Cheeseburger submarine sandwich",
    "Double cheeseburger",
    "Hamburger slider",
    "Hamburger",
    "Double hamburger",
    "Meatball",
    "Chiliburger",
    "Corned beef sandwich",
    "Reuben sandwich",
    "Bacon sandwich",
    "Roast beef sandwich",
    "Roast beef submarine sandwich",
    "Steak submarine sandwich",
    "Steak sandwich",
    "Fajita style beef sandwich",
    " Gyro sandwich",
    "Hamburger wrap sandwich",
    "Bacon sandwich",
    "Bacon on a biscuit",
    "Ham on a biscuit",
    "Ham sandwich",
    "Ham salad sandwich",
    "Hot ham",
    "Cuban sandwich",
    "Night half sandwich",
    "Pork sandwich",
    "Pork barbecue sandwich",
    "Chicken salad",
    "Chicken barbecue sandwich",
    "Chicken fillet sandwich",
    "Chicken fillet biscuit",
    "Chicken fillet wrap sandwich",
    "Chicken sub sandwich",
    "Buffalo chicken sub sandwich",
    "Turkey sandwich",
    "Turkey salad",
    "Turkey sub sandwich",
    "Fish sandwich",
    "Crab cake sandwich",
    "Salmon cake sandwich",
    "Salmon fried produce sandwich",
    "fish roll sandwich",
    "sardine sandwich",
    "tuna salad sandwich",
    "tuna salad sandwich",
    "tuna salad sandwich",
    "seafood salad sandwich",
    "lunch meat sandwich",
    "Bologna sandwich",
    "Corn dog",
    "Pig in a blanket",
    "Puerto Rican sandwich",
    "Hami sandwich",
    "Sausage on a biscuit",
    "Hot dog grilled cake sandwich",
    "Sausage balls",
    "Hot dog",
    " Cold cut sumarine sandwich",
    "Chicken noodle dish",
    "Chicken stew",
    "Chicken soup",
    "Frozen dinner",
    "Beef dinner",
    "Sirloin",
    "Sirloin",
    "Salisbury steak dinner",
    "Beef short ribs",
    "Chicken dish",
    "Teriyaki chicken",
    "Chicken dish",
    "Chicken with cream sauce",
    "Chicken with butter sauce",
    "Chicken with mushroom sauce",
    "Chicken with soy-based sauce",
    "Turkey dish",
    "Fish with lemon butter sauce",
    "Beef loaf dish",
    "Oxtail soup",
    "Broth",
    "Meatball soup",
    "Beef noodle soup",
    "Pho",
    "Pepperpot soup",
    "Menudo soup",
    "Beef vegetable soup",
    "Italian Wedding Soup",
    "Beef stroganoff soup",
    "Pork vegetable soup",
    "Bacon soup",
    "Mexican chicken stock soup broth",
    "Chicken rice soup",
    "Bird's nest soup",
    "Fish broth",
    "Fish soup",
    "Crab soup",
    "Oyster soup",
    "Fish soup",
    "Cod fish soup",
    "Lobster bisque ",
    "Lobster gumbo",
    "Oyster stew",
    "Salmon soup",
    "Shrimp soup",
    "Shrimp gumbo",
    "Seafood soup",
    "Broth",
    "Spanish vegetable soup",
    "Sauce",
    "Oysters sauce",
    "Mole sauce",
    "Egg",
    "Duck egg",
    "Goose egg",
    "Quail egg",
    "Egg salad",
    "Egg salad",
    "Huevos rancheros",
    "Egg casserole",
    "Egg foo yung",
    "Chicken egg foo yung",
    "Pork egg foo yung",
    "Shrimp egg foo yung",
    "Beef egg foo yung",
    "Ripe banana omelette",
    "Scrambled egg",
    "Egg a la Malaguena",
    "Egg omelette",
    "Egg salad sandwich",
    "Scrambled egg sandwich",
    "Egg drop soup",
    "Garlic egg soup",
    "Egg white omelette",
    "Egg white",
    "Meringue",
    "Egg replacer",
    "Beans",
    "White beans",
    "Black beans",
    "Broad beans",
    "Lima beans",
    "Pink beans",
    "Kinto beans",
    "Pinto beans",
    "Peruvian beans",
    "Soybeans",
    "Mung beans",
    "Dried beans",
    "Dried beans from fast food / restaurant",
    "Black bean salad",
    "Fried beans",
    "Bean sauce",
    "Layered sauce",
    "Hummus",
    "Black bean sauce",
    "Falafel",
    "Bean cake",
    "Peppers",
    "Black-eyed peas",
    "Chickpeas",
    "Peas",
    "Wasabi peas",
    "Lentils",
    "Bean chips",
    "Papad",
    "Sambar",
    "Lentils curry",
    "Soy nuts",
    "Soy chips",
    "Tofu",
    "Tofu",
    "Miso sauce",
    "Miso",
    "Natto",
    "Hoisin sauce",
    "Soy sauce",
    "Teriyaki sauce",
    "Worcestershire sauce",
    "Noodles",
    "Textured vegetable protein",
    "Frozen dessert",
    "Bean soup",
    "Beans",
    "Black bean soup",
    "Lima bean soup",
    "Soy soup",
    "Pinto bean soup",
    "Liquid from boiled kidney beans",
    "Peas",
    "Garbanzo beans",
    "Peas",
    "Pea soup",
    "Lentil soup",
    "Bacon strip",
    "Bacon pieces",
    "Vegetarian burger",
    "Sandwich spread",
    "Vegetarian pot pie",
    "Vegetarian chili",
    "Tofu",
    "Vegetarian casserole",
    "Vegetarian stroganoff",
    "Soy burger",
    "Hazelnut",
    "Almonds",
    "Brazil nuts",
    "Cashews",
    "Chestnuts",
    "Coconuts",
    "Hazelnuts",
    "Macadamia nuts",
    "Mixed nuts",
    "Peanuts",
    "Walnuts",
    "Pine nuts",
    "Pistachios",
    "Walnuts",
    "Almond butter",
    "Almond butter",
    "Cashew butter",
    "Peanut butter",
    "Soy nut butter",
    "Peanut sauce",
    "Peanut butter sandwich",
    "Coconut cream",
    "Coconut water",
    "Pumpkin seeds",
    "Sunflower seeds",
    "Tahini",
    "Flax seeds",
    "Chia seeds",
    "Carob chips ",
    "Bread",
    "Roll",
    "Focaccia",
    "Naan",
    "Garlic bread",
    "Bruschetta",
    "Pan Dulce",
    "Coffee cake",
    "Croissant",
    "Pastry",
    "Bagel",
    "Stuffed bread",
    "Stuffed bread",
    "Stuffed bread",
    "Breadsticks",
    "Croutons",
    "Muffin",
    "Melba toast",
    "Anisette toast",
    "Pannetone",
    "Zwieback toast",
    "Injera",
    "Biscuit",
    "Crumpet",
    "Muffin",
    "Cornbread",
    "Cornbread stuffing",
    "Cornbread muffin",
    "Cornmeal patties",
    "Corn pone",
    "Hush puppy ",
    "Johnnycake",
    "Spoon bread",
    "Tortilla",
    "Taco shell",
    "Arepa Dominicana",
    "Popover",
    "Cake batter",
    "Cake",
    "Cheesecake",
    "Snack cake",
    "Ice cream cake ",
    "Rum cake",
    "Cookie",
    "Cookie bar",
    "Pocky",
    "Marie biscuit",
    "Cookie",
    "Pie",
    "Mixed berry tart filling",
    "Sweet pizza",
    "Pie crust",
    "Vanilla wafer dessert base",
    "Blintz",
    "Cobbler",
    "Fritter",
    "Cream puff",
    "Air filled pastry",
    "Wheat flour pastry",
    "Crepe",
    "Tamale ",
    "Pie",
    "Baklava",
    "Basbousa",
    "Turnover",
    "Pastry",
    "Cheese pastry puffs",
    "Empanada",
    "Breakfast pastry",
    "Danish pastry",
    "Doughnut",
    "Donut holes",
    "Churros",
    "Breakfast tart",
    "Cereal",
    "Snack bar",
    "Breakfast bar",
    "Nutrition bar",
    "Cereal bar",
    "Crackers",
    "Graham crackers",
    "Chips",
    "Rice cake",
    "Popcorn cake",
    "Rice paper",
    "Corn nuts",
    "Corn chips",
    " Cheese flavored corn snacks",
    "Tortilla chips",
    "Snack mix",
    "Potato chips",
    "Pita chips",
    "Popcorn",
    "Popcorn chips",
    "Onion flavor rings",
    "Shrimp chips",
    "Pretzel",
    "Pretzel chips",
    "Multigrain chips",
    "Bagel chips",
    "Cracker chips",
    "Waffles",
    "French toast",
    "French toast sticks",
    "Chinese pancake",
    "Fritter",
    "Cake making",
    "Dosa",
    "Funnel cake",
    "Pasta",
    "Noodles",
    "Long rice noodles",
    "Rice noodles",
    "Barley",
    "Buckwheat groats",
    "Semolina",
    "Corn flour porridge",
    "Corn flour",
    "Corn flour dumpling",
    "Masa harina",
    "Millet",
    "Oatmeal",
    "Quinoa",
    "Rice",
    "Congee",
    "Yellow rice",
    "Cream of wheat",
    "Bulgur",
    "Couscous",
    "Whole wheat flakes",
    "Wheat flakes",
    "Oat bran flakes",
    "Cream of rye",
    "Granola",
    "Wheat germ",
    "Wheat bran",
    "Oats",
    "Oat bran",
    "Barley flakes",
    "Oatmeal cereal",
    "Rice flakes",
    "Brown rice flakes",
    "Gerber Alumni Finger Snack Cereal",
    "Burrito",
    "Chilaquiles",
    "Enchilada",
    "Taco",
    "Soft taco",
    "Mexican casserole",
    "Tamale casserole",
    "Nachos",
    "Gordita",
    "Chimichanga",
    "Quesadilla",
    "Taquito",
    "Fajita",
    "Pupusa",
    "Pizza",
    "White pizza",
    "Calzone",
    "Pizza rolls",
    "Breakfast pizza",
    "Egg roll",
    "Wonton",
    "Tamal on a sheet",
    "Meat turnover",
    "Cheese turnover",
    "Cornmeal roll",
    "Codfish roll",
    "Hayacas",
    "Cornflour coconut dessert",
    "Gnocchi",
    "Sweet bread dough",
    "Spanakopitta",
    "Quiche",
    "Spinach quiche",
    "Cheese quiche",
    "Turnover filling",
    "Vegetables in pastries",
    "Vegetables",
    "Croissant sandwich",
    "Vegetable submarine sandwich",
    "Chicken cornbread",
    "Cornmeal sauce",
    "Sauce",
    "Lasagna",
    "Ravioli",
    "Manicotti",
    "Stuffed shells",
    "Tortellini",
    "Cannelloni",
    "Chow fun noodles",
    "Lo mein",
    "Pad Thai",
    "Spaghetti",
    "Pasta",
    "Flavored pasta",
    "Noodle pudding",
    "Bibimbap",
    " Sushi",
    "Sushi roll",
    "Sushi roll tuna",
    "Seafood paella",
    "Soup rice",
    "Soup rice mixture",
    "Rice flour dumpling",
    "Boiled rice",
    "Fried rice",
    "Raisins",
    "Rice croquette",
    "Stuffed peppers",
    "Stuffed tomatoes",
    "Rice pilaf",
    "Dirty rice",
    "Flavored rice mix",
    "Flavored rice",
    "Spanish rice",
    "Rice sauce",
    "Rice dessert",
    "Upma",
    "Vada",
    "Tabbouleh",
    "Jelly sandwich",
    "Vegetable lasagna",
    "Pumpkin lasagna",
    "Linguini",
    "Beef enchilada dish",
    "Beef enchilada",
    "Cheese enchilada",
    "Soup",
    "Noodle soup",
    "Rice soup",
    "Barley soup",
    "Beef dumpling soup",
    "Beef rice soup",
    "Noodles",
    "Matzo ball soup",
    "Instant soup",
    " Wonton soup",
    "Sopa seca",
    "Sopa Seca de Fideo",
    "Sopa de Fideo Aguada",
    "Sopa seca de arroz",
    "Sopa de tortilla",
    "Meat substitute",
    "Clementine",
    "Grapefruit",
    " Kumquat",
    "Lemon",
    "Lemon pie filling",
    "Lime",
    "Orange",
    "Tangerine",
    "Grapefruit juice",
    "Lemon juice",
    "Orange juice",
    "Tangerine juice",
    "Juice mix ",
    "Fruit mix",
    "Apple",
    "Apricot",
    "Blueberry",
    "Cherry",
    "Banana chips",
    "Currants",
    "Cranberry",
    "Date",
    "Fig",
    "Mango",
    "Papaya",
    "Peach",
    "Pear",
    "Persimmon",
    "Pineapple",
    "Prunes",
    "Raisins",
    "Tamarind",
    "Fruit",
    "Applesauce",
    "Apple pie filling",
    "Avocado",
    "Banana",
    "Melon",
    "Star fruit",
    "Cassaba melon",
    "Scherry pie filling",
    "Grape",
    "Guava",
    "Kiwi fruit",
    "Lychee",
    "Honeydew melon",
    "Nectarine",
    "Passion fruit",
    "Plum",
    "Pomegranate",
    "Rhubarb",
    "Watermelon",
    "Strawberry",
    "Blackberry",
    "Blueberry filling",
    "Cranberry sauce",
    "Raspberry",
    "Strawberry",
    "Fruit salad",
    "Fruit cocktail",
    "Apple salad",
    "Lime soufflé",
    "Guacamole",
    "chutney",
    "Pineapple salad",
    "Frozen juice bar",
    "Sorbet ",
    "Juice",
    "Cranberry juice blend",
    "Cider",
    "Apple juice",
    "Blackberry juice",
    "Blueberry juice",
    "Cranberry juice",
    "Grape juice",
    "Papaya juice",
    " Passion fruit juice",
    "Pineapple juice",
    "Pomegranate juice",
    "Prune juice",
    "Strawberry juice",
    "Watermelon juice",
    "Fruit nectar",
    "Apricot nectar",
    "Banana nectar",
    "Melon nectar",
    "Guava nectar",
    "Mango nectar",
    "Peach nectar",
    "Papaya nectar",
    "Passion fruit nectar",
    "Pear nectar",
    "Cinnamon apple",
    "Vinegar",
    "Fruit bar",
    "Tropical fruit mix ",
    "Apple",
    "Banana",
    "Peach",
    "Pear",
    "Prune",
    "Mixed fruit juice",
    "Orange-apple-banana juice",
    "Pear juice",
    "Apple-sweet potato juice",
    "Orange-carrot juice",
    "Banana juice",
    "Plum",
    "Apricot",
    "Fruit dessert",
    "Fruit Supreme dessert",
    "Apple yoghurt dessert",
    "Banana apple dessert",
    "Blueberry yoghurt dessert",
    "Mixed fruit yoghurt dessert",
    "Cherry cobbler",
    "Peach cobbler",
    "Banana yoghurt dessert",
    "Cherry vanilla pudding",
    "Dutch apple dessert",
    "Peach yoghurt dessert",
    "Pineapple dessert",
    "Mango dessert",
    "Tutti-fruit pudding",
    "Fruit flavored snack ",
    "Potatoes",
    "Boiled potatoes",
    "Just potatoes from Puerto Rican mixed dishes",
    "Puerto Rican stuffed french fries",
    "Potatoes from Puerto Rican beef stew",
    "Puerto Rican chicken fricas",
    "Potato sticks",
    " Vegetable chips",
    "Potato skins without topping",
    "Potato skins",
    "Potato patties",
    "Potato tots",
    "Potato salad",
    "Potato pancakes",
    "Lefse",
    "Potato soup",
    "Potato soup",
    "Banana soup",
    "Banana",
    "Ripe banana",
    "Banana chips",
    "Green banana",
    "Cassava",
    "Yuca fries",
    "Yam",
    "Yam buns; Puerto Rican style",
    "Celery",
    "Taro",
    "Poi",
    "Taro chips",
    "Beet greens",
    "Broccoli raab",
    "Chard",
    "Dandelion greens",
    "Lettuce",
    "Caesar salad",
    "Escarole",
    "Cabbage",
    "Lamb quarter",
    "Mustard sprouts",
    "Mustard greens",
    "Poke greens",
    "Radicchio",
    "Spinach soufflé ",
    "Palak Paneer",
    "Channa Saag",
    "Taro leaves",
    "Turnip greens",
    "Turrnip greens",
    "Watercress",
    "Bitter melon",
    "Sweet potato",
    "Broccoli",
    "Broccoli",
    "Broccoli casserole",
    "Roast broccoli",
    "Broccoli soup",
    "Broccoli cheese soup",
    "Watercress broth",
    "Spinach soup",
    "Dark green leafy vegetable soup",
    "Carrot",
    " Beetroot juice",
    "Carrot juice",
    "Peas",
    "Pumpkin",
    "Winter squash",
    "Pumpkin pie",
    "Pumpkin",
    "Sweet potato fries",
    "Sweet potato chips",
    "Sweet potatoes tots",
    "Carrot soup",
    "Carrot",
    "Tomato",
    "Fried green tomatoes",
    "Tomato",
    "Sun dried tomatoes",
    "Tomato juice",
    "Tomato juice cocktail",
    "Ketchup",
    "Tomato chili sauce",
    "Salsa",
    "Taco sauce",
    "Enchilada sauce",
    "Salsa verde",
    "Hot Thai sauce",
    "Vodka sauce",
    "BBQ sauce",
    "Buffalo sauce",
    "Steak sauce",
    "Cocktail sauce",
    "Puerto Rican seasoning",
    "Puerto Rican seasoning without ham",
    "Tomato aspic",
    "Tomato soup",
    "Beef noodle soup with tomatoes",
    "Beef rice soup with tomatoes",
    "Noodle soup with tomatoes",
    "rice soup with tomatoes",
    "Vegetable soup with tomatoes",
    "Tomato sandwich",
    "Raw vegetables",
    "Sprout",
    "Alfalfa sprouts",
    "Artichoke",
    "Asparagus",
    "Bean sprouts",
    "Green beans",
    "Beets",
    "Brussels sprouts",
    "Cactus",
    "Cauliflower",
    "Celery",
    "Fennel bulb",
    "Basil",
    "Chives",
    "Coriander",
    "Corn",
    "Cucumber",
    "Eggplant",
    "Garlic",
    "Jicama",
    "Kohlrabi",
    "Leek",
    "Lettuce",
    "Mixed salad greens",
    "Mushroom",
    "Onion",
    "Parsley",
    "Green peas",
    "Pepper",
    "Radish",
    "Turnip",
    "Seaweed",
    "Snow peas",
    "Summer squash",
    "Mixed vegetable broth",
    "Celery juice",
    "Broccoli salad",
    "Broccoli coleslaw",
    "Coleslaw",
    "Cucumber salad",
    "Cucumber salad made",
    "Seven-layer salad",
    "Greek Salad",
    "Spinach salad",
    "Cobb salad",
    "Aloe vera juice drink",
    "Artichoke",
    "Bamboo sprouts",
    "Fried green beans",
    "Yellow string beans",
    "Breadfruit",
    "Hominy",
    "Lotus root",
    "Mushroom",
    "Okra",
    " Luffa",
    "Hearts of palm",
    "Parsnip",
    "Peppers",
    "Hot peppers",
    "Pimiento",
    "Daikon radish",
    "Salsify",
    "Sauerkraut",
    "Snow peas",
    "Spaghetti squash",
    "Water Chesnut",
    "Winter melon",
    "Yeast",
    "Yeast extract spread",
    "Bean salad",
    "Classic mixed vegetables",
    "Ratatouille",
    "Asian stir-fry vegetables",
    "Jai",
    "Vegetable mix",
    "Green bean casserole",
    "Fried cauliflower",
    "Chiles rellenos",
    "Stuffed jalapeno peppers",
    "Corn fritters",
    "Fried eggplant",
    "Eggplant sauce",
    "Eggplant parmesan casserole",
    "Fried mushrooms",
    " Fried okra",
    "Fried onion rings",
    "Pea salad",
    "Fried summer squash",
    "Creamy christophine",
    "Meatless vegetable casserole",
    "Vegetable tempura",
    "Pakora",
    "Vegetable curry",
    "Flavour",
    "Kimchi",
    "Pickle",
    "Ginger root",
    "Horseradish",
    "Mustard",
    "Honey mustard sauce",
    "Olive",
    "Olive tapenade",
    "Hot pepper sauce",
    "Radish",
    "Wasabi paste ",
    "Pumpkin",
    "Asparagus soup",
    "Beetroot soup",
    "Cabbage soup",
    "Celery soup",
    "Corn soup",
    "Gazpacho",
    "Leek soup",
    "Mushroom soup",
    "Onion soup",
    "Pea soup",
    "Vegetable soup",
    "Pumpkin soup",
    "Chav soup",
    "Seaweed soup",
    "Vegetable noodle soup",
    "Vegetable noodle soup",
    "Beef noodle soup with vegetables",
    "Beef noodle soup with vegetables",
    "Vegetable rice soup",
    "Chicken rice soup with vegetables",
    "Vegetarian vegetable soup",
    "Vegetable broth",
    "Sweet potatoes",
    "Mixed vegetables",
    "Potatoes",
    "Vegetables",
    "Stuffed fried potatoes",
    " Chicken fritters with potatoes",
    "Green bananas",
    "Ripe banana fritters",
    "Cassava Pastels",
    "Stuffed cassava fritters",
    "Stuffed plate fritters",
    "Puerto Rican pastels",
    "Stuffed cabbage",
    "Spanish stew",
    " Puerto Rican stew",
    "Herbal smoothie",
    "Table butter",
    "Butter",
    "Margarine",
    "Margarine-oil mixture",
    "Butter substitute",
    "Butter-oil mixture",
    "Oil",
    "Animal fat",
    "Pork fat",
    "Fat ",
    "Ghee",
    "Garlic sauce",
    "Lemon butter sauce",
    "Hollandaise sauce",
    "Tartar sauce",
    "Horseradish sauce",
    "Pesto sauce",
    "Frying sauce",
    "Curry sauce",
    "Honey oil",
    "Vegetable oil",
    "Almond oil",
    "Coconut oil",
    "Corn oil",
    "Cottonseed oil",
    "Linseed oil",
    "Olive oil",
    "Peanut oil",
    "Canola oil",
    "Safflower oil",
    "Sesame oil",
    "Soybean oil",
    "Sunflower oil",
    "Walnut oil",
    "Wheat germ oil",
    "Salad dressing",
    "Blue",
    "Caesar dressing",
    "Cole salad dressing",
    "French",
    "Honey mustard dressing",
    "Italian dressing",
    "Mayonnaise",
    "Vegan mayonnaise",
    "Russian dressing",
    "Mayonnaise type salad dressing",
    "Avocado dressing",
    "Cream dressing",
    "Poppyseed seed sauce",
    "Sesame sauce",
    "Thousand Island sauce",
    "Yogurt sauce",
    "Korean sauce",
    "Cream sauce",
    "Soy-based sauce",
    "Tomato sauce",
    "Sugar",
    "Sugar substitute",
    "Syrup",
    "Prepe syrup",
    "Corn syrup",
    "Blueberry syrup",
    "Chocolate syrup",
    "Simple syrup",
    "Strawberry drink syrup",
    "Honey",
    "Agave liquid sweetener",
    "Molasses",
    "Topping",
    "Icing",
    "Caramel sauce",
    "Chocolate sauce",
    "Dessert dip",
    "Sweet sauce",
    "Duck sauce",
    "Jelly",
    "Jam",
    "Fruit butter",
    "Marmalade",
    "Guava paste",
    "Sweet potato paste",
    "Bean paste",
    "Gelatin dessert",
    "Gelatin salad",
    "Yokan",
    "Coconut cream cake",
    "Haupia",
    "Italian Ice",
    "Popsicle",
    "Freezer pop",
    "Snow cone",
    "Candy",
    "M&M's Almond Chocolate Chip Candies",
    "Caramel bites",
    "Caramel",
    "Caramel candy",
    "Rolo",
    "Toblerone",
    "TWIX Caramel Cookie Bars ",
    "TWIX Chocolate Fudge Cookie Bars",
    "TWIX Peanut Butter Cookie Bars",
    "Whatchamacallit",
    "Espresso coffee beans",
    "Milk chocolate candy",
    "Kit Kat",
    "Chocolate",
    "Chocolate candy",
    "Kit Layer White",
    "Mexican chocolate",
    "Coconut sugar",
    "Fondant",
    "Fruit peel",
    "Date sugar",
    "Soft fruit candies",
    "Fruit leather",
    "Fun Fruits Creme Supremes",
    "Tamarind sugar ",
    "Fruit snack candy",
    "Yogurt coated fruit snack candy",
    "Yogurt coated fruit snack candy",
    "Gummies",
    "Fudge",
    "SNICKERS Bar",
    "Baby Ruth",
    "100 GRAND Bar",
    "Halva ",
    "Honey combed hard candy",
    "Butterfinger",
    "Butterfinger Crisp",
    "Chocolate flavored sprinkles",
    "Ladoo",
    "Licorice",
    "Marshmallow",
    "Nougat",
    "MILKY WAY Bar",
    "MILKY WAY MIDNIGHT Bar",
    "MARS Almond Bar",
    "3 Musketeers Bar",
    "3 Musketeers Truffle Crisp Bar",
    "Hazelnut Roll",
    "Candied Pecans",
    "M&M's Peanut Butter Chocolate Candies",
    "M&M's Peanut Butter Chocolate Chip Candies",
    "Peanut bar",
    "Planters Peanut Bar",
    "Peanut Brittle",
    "Peanut Bar",
    "Reese's Peanut Butter Bar",
    "Reese's Pieces",
    "Reese's Bars",
    "Reese' in Quick Break",
    "Reese's Crunchy Bar",
    "Peanut butter bites",
    "Pralines",
    "Pineapple candy",
    "Sesame Crunch",
    "Hard candy",
    "Butterscotch hard candy",
    "Skittles",
    "Sugar coated chocolate discs",
    "M&M's Milk Chocolate Candies",
    "Six-pack",
    "Easter egg",
    "M&M's Pretzel Chocolate Candies",
    "Fudge",
    "Toffee",
    "Truffle",
    "Wax candy ",
    "Dietetics",
    "Gum",
    "Coffee",
    "Frozen coffee drink",
    "Frozen mocha coffee drink",
    "Iced Coffee",
    "Coffee substitute",
    "Chicory drink",
    "Cereal drink",
    "Tea",
    "Corn drink",
    "Iced Tea/Lemonade juice drink",
    "Soft drink",
    "Soda water",
    "Juice drink",
    "Tamarind drink",
    "Fruit punch",
    "Lemonade",
    "Fruit flavored drink",
    "Juice drink",
    "Frozen daiquiri mix",
    "Pina Colada",
    "Margarita mix",
    "Slush frozen drink",
    "Cranberry juice drink",
    "Grape juice drink",
    "Orange juice drink",
    "Apple juice drink",
    "Pomegranate juice drink",
    "Horchata drink",
    "Oatmeal drink",
    "Cane sugar drink",
    "Cornflour drink",
    "Wine",
    "Non-alcoholic malt drink",
    "Shirley Temple",
    "Sports drink ",
    "Beer",
    "Alcoholic malt beverage",
    "Hard cider",
    "Cozy",
    "Cocktail",
    "Alexander",
    "Bacardi cocktail",
    "Bloody Mary",
    "Canadian Club",
    "Cape Cod",
    "Daiquiri",
    "Gelatin shot",
    "Gimlet",
    "Gin",
    "Grasshopper",
    "Hound",
    "Highball",
    "Jagerbomb",
    "Kamikaze",
    "Manhattan",
    "Margarita",
    "Martini",
    "Mimosa",
    "Mint julep",
    "Mojito",
    "Old Fashioned",
    "Orange Blossom",
    "Rob Roy",
    "Rusty Nail",
    "Salt Dog",
    "Screwdriver",
    "Sea Breeze",
    "Seven",
    "Tom Collins",
    "Whiskey sour",
    "Whisky",
    "Rum",
    "Brandy",
    "Vodka",
    "Sloe gin fizz",
    "Black Russian",
    "White Russian",
    "Champagne punch",
    "Singapore Sling",
    "Stinger",
    "Mai Tai",
    "Tequila Sunrise",
    "Gin Rickey",
    "Golden Cadillac",
    "Long Island iced tea",
    "Fuzzy Belly",
    "Irish Coffee",
    "Liqueur",
    "Frozen daiquiri",
    "Frozen margarita",
    "Gin fizz",
    "Zombie",
    "Wine cooler",
    "Sangria",
    "Scotch",
    "Rum cooler",
    "Tequila",
    "Water",
    "Nutritious drink",
    "Nutritional powder mix",
    "Energy Drink",
    "Liquid replacement",
    "Cheese as ingredient in sandwiches",
    "Breakfast meat as ingredient in omlette",
    "Fish fillet",
    "Bread",
    "Wheat bread as ingredient in sandwiches",
    "Wheat bun as ingredient in sandwiches",
    "Green pepper",
    "Red pepper",
    "Dark green vegetables as ingredient in omelette ",
    "Tomato as ingredient in omlette",
    "Other vegetables as ingredient in omlette",
    "Vegetables as ingredient in curry",
    "Sauce as ingredient in hamburger",
    "Industrial oil as ingredient in food"
  ];

  Future<void> createData(Map<String, dynamic> data) async {
    await _firestoreService.createData(data);
  }

  Future<Map<String, dynamic>?> readData(String documentId) async {
    return await _firestoreService.readData(documentId);
  }

  Future<void> updateData(
      String documentId, Map<String, dynamic> newData) async {
    await _firestoreService.updateData(documentId, newData);
  }

  Future<void> deleteData(String documentId) async {
    await _firestoreService.deleteData(documentId);
  }

  Future<String?> fetchNutritionBody(String foodName) async {
    String query = foodName.toLowerCase().tr().toString();
    String encodedQuery = Uri.encodeQueryComponent(query);

    var url = Uri.parse(
        "https://api.api-ninjas.com/v1/nutrition?query=$encodedQuery");

    var response = await http.get(
      url,
      headers: {
        'X-Api-Key': nutritionApiKey,
      },
    );

    if (response.statusCode == 200) {
      return response.body; // Response'un body değerini döndür
    } else {
      return null;
    }
  }

  Future<double?> getCaloriesFromFood(String foodName) async {
    var foodBody = await fetchNutritionBody(foodName);

    if (foodBody != null) {
      var jsonResponse = json.decode(foodBody);
      if (jsonResponse is List && jsonResponse.isNotEmpty) {
        var firstItem = jsonResponse[0];
        if (firstItem is Map<String, dynamic> &&
            firstItem.containsKey('calories')) {
          var calories = firstItem['calories'];
          if (calories is double) {
            return calories;
          } else if (calories is int) {
            return calories.toDouble();
          }
        }
      }
    }
    // Eğer herhangi bir değer bulunamazsa veya tür uyumsuzluğu varsa null döndür
    return null;
  }

  Future<void> removeNullValues() async {
    List<String> foodsToRemove = [];

    for (var food in foods) {
      var calories = await getCaloriesFromFood(food);
      if (calories == null) {
        foodsToRemove.add(food);
      }
    }

    // Test etmek için konsola yazdırabiliriz
    print("Yanit Yok Listesi :");
    print(foodsToRemove);
  }

  void addCaloriesTaken(User user, String foodName) async {
    double? newCalories = await getCaloriesFromFood(foodName);
    if (newCalories != null) {
      if (user.userDiet == null) {
        UserDiet userDiet = UserDiet(
          calories_taken: newCalories,
          calculation_date: DateTime.now(),
        );
        user.userDiet = userDiet;
      } else {
        user.userDiet!.calories_taken =
            (user.userDiet!.calories_taken ?? 0) + newCalories;
      }
    }
  }

  Future<List<String>> getAllTurkishFoods() async {
    List<String> foods = await localFood.turkceYemekler();
    return foods;
  }

  Future<void> processControl() async {
    for (var item in foods) {
      await fetchAndDeleteIfNull(item);
    }
  }

  Future<void> fetchAndDeleteIfNull(String food) async {
    String? response = await fetchNutritionBody(food);

    if (response == null || checkNameEquality(response, food)) {
      print(food);
    }
  }

  bool checkNameEquality(String response, String food) {
    var jsonResponse = json.decode(response);

    if (jsonResponse is Map<String, dynamic> &&
        jsonResponse.containsKey('name')) {
      var name = jsonResponse['name'];

      if (name is String) {
        return name.toLowerCase() != food.toLowerCase();
      }
    }

    return false;
  }
}
